/**
 * EmojLock Binary Payload & Secret Engine
 *
 * Binary Layout (Version 1):
 * [0..3]   MAGIC           : 4 bytes ("EMJL" = 0x45, 0x4D, 0x4A, 0x4C)
 * [4]      VERSION         : 1 byte  (0x01)
 * [5]      FLAGS           : 1 byte  (bit0: HAS_PASSWORD, bit1: VIEW_ONCE, bit2: DECOY_MODE)
 * [6..9]   CIPHERTEXT_LEN  : 4 bytes (UInt32 Big-Endian)
 * [10..25] SALT            : 16 bytes (cryptographic salt)
 * [26..37] NONCE (IV)      : 12 bytes (AES-GCM 96-bit IV)
 * [38..]   CIPHERTEXT      : CIPHERTEXT_LEN bytes (includes 16-byte AES-GCM tag)
 *
 * Total Header Size: 4 + 1 + 1 + 4 + 16 + 12 = 38 bytes.
 * Minimum Payload Size: 38 bytes (header) + 16 bytes (tag) = 54 bytes.
 */

import { deriveKey, encryptBytes, decryptBytes, getRandomBytes } from './crypto';
import { encodeBytesToEmoji, decodeEmojiToBytes, DECOY_PREFIXES, DECOY_SUFFIXES } from './emojiCodec';
import { generateFingerprintFromBytes } from './fingerprint';
import {
  EncodeOptions,
  EncodeResult,
  DecodeOptions,
  DecodeResult,
  PayloadHeader,
  DecodeError
} from '../types';

export const MAGIC_BYTES = new Uint8Array([0x45, 0x4D, 0x4A, 0x4C]); // 'EMJL'
export const CURRENT_VERSION = 0x01;

export const FLAG_HAS_PASSWORD = 0x01;
export const FLAG_VIEW_ONCE    = 0x02;
export const FLAG_DECOY_MODE   = 0x04;

export const HEADER_SIZE = 4 + 1 + 1 + 4 + 16 + 12; // 38 bytes
export const MIN_PAYLOAD_SIZE = HEADER_SIZE + 16;   // 54 bytes

/**
 * Finds the starting offset of the MAGIC_BYTES sequence in a byte array.
 */
export function findMagicOffset(bytes: Uint8Array): number {
  if (bytes.length < 4) return -1;
  for (let i = 0; i <= bytes.length - 4; i++) {
    if (
      bytes[i] === MAGIC_BYTES[0] &&
      bytes[i + 1] === MAGIC_BYTES[1] &&
      bytes[i + 2] === MAGIC_BYTES[2] &&
      bytes[i + 3] === MAGIC_BYTES[3]
    ) {
      return i;
    }
  }
  return -1;
}

/**
 * Packs metadata, salt, nonce, and ciphertext into the standard EmojLock binary buffer.
 */
export function packPayload(
  version: number,
  flags: number,
  salt: Uint8Array,
  nonce: Uint8Array,
  ciphertext: Uint8Array
): Uint8Array {
  const ciphertextLength = ciphertext.length;
  const totalLength = HEADER_SIZE + ciphertextLength;
  const payload = new Uint8Array(totalLength);

  let offset = 0;
  // 1. Magic bytes (4 bytes)
  payload.set(MAGIC_BYTES, offset);
  offset += 4;

  // 2. Version (1 byte)
  payload[offset++] = version;

  // 3. Flags (1 byte)
  payload[offset++] = flags;

  // 4. Ciphertext Length (4 bytes, UInt32 Big Endian)
  const view = new DataView(payload.buffer, payload.byteOffset, payload.byteLength);
  view.setUint32(offset, ciphertextLength, false);
  offset += 4;

  // 5. Salt (16 bytes)
  payload.set(salt, offset);
  offset += salt.length;

  // 6. Nonce (12 bytes)
  payload.set(nonce, offset);
  offset += nonce.length;

  // 7. Ciphertext (includes AES-GCM tag)
  payload.set(ciphertext, offset);

  return payload;
}

/**
 * Extracts and unpacks the raw EmojLock payload from an arbitrary byte sequence (handling framing/decoys).
 */
export function extractAndUnpackPayload(rawBytes: Uint8Array): {
  header: PayloadHeader;
  cleanPayloadBytes: Uint8Array;
} {
  const magicOffset = findMagicOffset(rawBytes);
  if (magicOffset === -1) {
    throw createDecodeError(
      'INVALID_FORMAT',
      'Invalid signature. This emoji sequence was not generated by EmojLock or is missing the header.'
    );
  }

  const bytes = rawBytes.slice(magicOffset);
  if (bytes.length < MIN_PAYLOAD_SIZE) {
    throw createDecodeError(
      'INVALID_FORMAT',
      'The provided emoji string is incomplete or truncated.'
    );
  }

  // Version
  const version = bytes[4];
  if (version !== CURRENT_VERSION) {
    throw createDecodeError(
      'UNSUPPORTED_VERSION',
      `Unsupported secret version (v${version}). Please use an updated version of EmojLock.`
    );
  }

  // Flags
  const flags = bytes[5];
  const hasPassword = (flags & FLAG_HAS_PASSWORD) !== 0;
  const viewOnce    = (flags & FLAG_VIEW_ONCE) !== 0;
  const decoyMode   = (flags & FLAG_DECOY_MODE) !== 0;

  // Ciphertext Length
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const ciphertextLength = view.getUint32(6, false);

  if (ciphertextLength < 16) {
    throw createDecodeError(
      'CORRUPT_PAYLOAD',
      'Invalid ciphertext length specified in header.'
    );
  }

  const expectedTotalLength = HEADER_SIZE + ciphertextLength;
  if (bytes.length < expectedTotalLength) {
    throw createDecodeError(
      'INVALID_FORMAT',
      `Incomplete secret. Expected ${expectedTotalLength} payload bytes, but received ${bytes.length}.`
    );
  }

  // Extract Salt (16 bytes) and Nonce (12 bytes)
  let offset = 10;
  const salt = bytes.slice(offset, offset + 16);
  offset += 16;

  const nonce = bytes.slice(offset, offset + 12);
  offset += 12;

  const ciphertext = bytes.slice(offset, offset + ciphertextLength);
  const cleanPayloadBytes = bytes.slice(0, expectedTotalLength);

  return {
    header: {
      version,
      hasPassword,
      viewOnce,
      decoyMode,
      salt,
      nonce,
      ciphertext
    },
    cleanPayloadBytes
  };
}

/**
 * Backward-compatible helper for unpacking without clean payload extraction.
 */
export function unpackPayload(payloadBytes: Uint8Array): PayloadHeader {
  return extractAndUnpackPayload(payloadBytes).header;
}

/**
 * Creates an Additional Authenticated Data (AAD) header buffer to prevent header tampering.
 * Covers: MAGIC (4) + VERSION (1) + FLAGS (1) + CIPHERTEXT_LEN (4) = 10 bytes.
 */
function createAAD(version: number, flags: number, ciphertextLength: number): Uint8Array {
  const aad = new Uint8Array(10);
  aad.set(MAGIC_BYTES, 0);
  aad[4] = version;
  aad[5] = flags;
  const view = new DataView(aad.buffer, aad.byteOffset, aad.byteLength);
  view.setUint32(6, ciphertextLength, false);
  return aad;
}

/**
 * High-level function: Encrypts a message and encodes it into an emoji string.
 */
export async function encodeSecret(options: EncodeOptions): Promise<EncodeResult> {
  const { message, password, decoyMode = false, viewOnce = false } = options;

  if (!message || message.trim().length === 0) {
    throw new Error('Please enter a message to encode.');
  }

  const hasPassword = Boolean(password && password.length > 0);

  // Set binary flags
  let flags = 0;
  if (hasPassword) flags |= FLAG_HAS_PASSWORD;
  if (viewOnce)    flags |= FLAG_VIEW_ONCE;
  if (decoyMode)   flags |= FLAG_DECOY_MODE;

  // Generate cryptographically secure random salt and nonce
  const salt = getRandomBytes(16);
  const nonce = getRandomBytes(12);

  // Derive key using PBKDF2-SHA-256
  const key = await deriveKey(hasPassword ? password! : '', salt);

  // Convert plaintext message to UTF-8
  const textEncoder = new TextEncoder();
  const plaintextBytes = textEncoder.encode(message);

  // Expected ciphertext length: plaintext + 16 bytes auth tag
  const expectedCiphertextLen = plaintextBytes.length + 16;

  // Bind AAD to header (Magic + Version + Flags + Ciphertext Length)
  const aad = createAAD(CURRENT_VERSION, flags, expectedCiphertextLen);

  // Encrypt using AES-256-GCM
  const ciphertext = await encryptBytes(plaintextBytes, key, nonce, aad);

  // Pack binary payload
  const binaryPayload = packPayload(CURRENT_VERSION, flags, salt, nonce, ciphertext);

  // Generate cryptographic fingerprint from the clean binary payload
  const fingerprint = await generateFingerprintFromBytes(binaryPayload);

  // Convert binary to curated emojis
  let emojiString = encodeBytesToEmoji(binaryPayload);

  // If Decoy Mode is requested, apply subtle conversational framing
  if (decoyMode) {
    const randomPrefix = DECOY_PREFIXES[Math.floor(Math.random() * DECOY_PREFIXES.length)];
    const randomSuffix = DECOY_SUFFIXES[Math.floor(Math.random() * DECOY_SUFFIXES.length)];
    emojiString = `${randomPrefix}${emojiString}${randomSuffix}`;
  }

  return {
    emojiString,
    fingerprint,
    payloadLength: binaryPayload.length,
    emojiCount: binaryPayload.length,
    hasPassword,
    viewOnce,
    decoyMode
  };
}

/**
 * High-level function: Decodes and decrypts an emoji secret string.
 */
export async function decodeSecret(options: DecodeOptions): Promise<DecodeResult> {
  const { emojiString, password = '' } = options;

  if (!emojiString || emojiString.trim().length === 0) {
    throw createDecodeError('EMPTY_INPUT', 'Please paste an emoji secret.');
  }

  // 1. Decode emojis to raw bytes
  let rawBytes: Uint8Array;
  try {
    rawBytes = decodeEmojiToBytes(emojiString);
  } catch (err: any) {
    console.warn('Emoji decoding failed:', err);
    throw createDecodeError(
      'INVALID_FORMAT',
      'The provided text does not contain valid EmojLock emoji data.'
    );
  }

  // 2. Unpack and validate structure (scans past decoy framing if present)
  const { header, cleanPayloadBytes } = extractAndUnpackPayload(rawBytes);

  // 3. Compute fingerprint on the clean extracted payload
  const fingerprint = await generateFingerprintFromBytes(cleanPayloadBytes);

  // 4. Check if password is required but not provided
  if (header.hasPassword && (!password || password.length === 0)) {
    throw createDecodeError(
      'PASSWORD_REQUIRED',
      'This secret is password-protected. Please enter the password to decrypt.',
      fingerprint
    );
  }

  // 5. Derive key
  const key = await deriveKey(header.hasPassword ? password : '', header.salt);

  // 6. Decrypt ciphertext with AAD validation
  let flags = 0;
  if (header.hasPassword) flags |= FLAG_HAS_PASSWORD;
  if (header.viewOnce)    flags |= FLAG_VIEW_ONCE;
  if (header.decoyMode)   flags |= FLAG_DECOY_MODE;
  const aad = createAAD(header.version, flags, header.ciphertext.length);

  try {
    const decryptedBytes = await decryptBytes(header.ciphertext, key, header.nonce, aad);

    // Decode strictly as UTF-8
    const textDecoder = new TextDecoder('utf-8', { fatal: true });
    const plaintext = textDecoder.decode(decryptedBytes);

    return {
      plaintext,
      fingerprint,
      version: header.version,
      hasPassword: header.hasPassword,
      viewOnce: header.viewOnce,
      decoyMode: header.decoyMode,
      verified: true
    };
  } catch (err: any) {
    console.warn('Decryption or UTF-8 decoding failed:', err);
    // If decryption fails (authentication tag mismatch or invalid UTF-8)
    if (header.hasPassword) {
      throw createDecodeError(
        'WRONG_PASSWORD_OR_CORRUPT',
        'Unable to decrypt this secret. Check the password or verify that the emoji payload was not modified.',
        fingerprint
      );
    } else {
      throw createDecodeError(
        'CORRUPT_PAYLOAD',
        'Unable to decrypt this secret. The emoji payload appears to be corrupted or modified in transit.',
        fingerprint
      );
    }
  }
}

/**
 * Standalone core encode function.
 * Plaintext -> UTF-8 -> AES-256-GCM -> Binary payload -> Emoji Base256 -> Emoji string.
 */
export async function encodeMessage(message: string, password?: string): Promise<string> {
  const result = await encodeSecret({
    message,
    password: password || '',
    decoyMode: false,
    viewOnce: false
  });
  return result.emojiString;
}

/**
 * Standalone core decode function.
 * Emoji string -> Emoji Base256 -> Binary payload -> AES-256-GCM -> UTF-8 -> Plaintext.
 */
export async function decodeMessage(emojiString: string, password?: string): Promise<string> {
  const result = await decodeSecret({
    emojiString,
    password: password || ''
  });
  return result.plaintext;
}

/**
 * Inspects a payload to check if it's password protected without attempting full decryption.
 */
export function inspectEmojiPayload(emojiString: string): {
  isValid: boolean;
  hasPassword?: boolean;
  viewOnce?: boolean;
  decoyMode?: boolean;
  version?: number;
  error?: string;
} {
  try {
    const rawBytes = decodeEmojiToBytes(emojiString);
    const { header } = extractAndUnpackPayload(rawBytes);
    return {
      isValid: true,
      hasPassword: header.hasPassword,
      viewOnce: header.viewOnce,
      decoyMode: header.decoyMode,
      version: header.version
    };
  } catch (e: any) {
    return {
      isValid: false,
      error: e?.message || 'Invalid payload'
    };
  }
}

function createDecodeError(code: DecodeError['code'], message: string, details?: string): DecodeError {
  return { code, message, details };
}
